### ISSUE TITLE
AFL stuck "spinning up fork server"

### ISSUE THREAD

**Issue by icryo** [PacktPublishing/Fuzzing-Against-the-Machine#1]
Chapter 7, the snapshot is taken successfully but when opening it in AFL I'm timing out despite me increasing the limits.  Perhaps I'm missing a step?
Issue is discussed here, https://github.com/FirmWire/FirmWire/issues/26 & https://github.com/FirmWire/FirmWire/pull/28

**Comment by icryo** [comment]
Fixed by passing in `--restore-snapshop gsm_fuzz_base` to AFL, the current version does not contain that argument. 
Consider adding it to the final version of the book.

**Comment by jeppojeps** [comment]
Thanks for the errata @icryo, what I wonder is how you get a copy of the book before the release, given that we don't even have it yet.
